name: CI with PVS-Studio

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build SimpleCalc.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test CalculatorApp.Tests/CalculatorApp.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Download and extract PVS-Studio
        run: |
          wget https://files.viva64.com/pvs-studio-latest.tgz
          tar -xzf pvs-studio-latest.tgz

      - name: Verify PVS-Studio binaries
        run: |
          PVS_DIR=$(find . -maxdepth 1 -type d -name 'pvs-studio-*-x86_64')
          echo "Using PVS-Studio from $PVS_DIR"
          ls -la "$PVS_DIR/bin"

      - name: Run PVS-Studio analysis (no install)
        run: |
          PVS_DIR=$(find . -maxdepth 1 -type d -name 'pvs-studio-*-x86_64')
          echo "Running analyzer from $PVS_DIR/bin"
          "$PVS_DIR/bin/pvs-studio-analyzer" analyze \
            --output-file=pvs-report.log \
            -- msbuild SimpleCalc.sln /t:Rebuild /p:Configuration=Release /p:UseSharedCompilation=false

          echo "Converting log to errorfile"
          "$PVS_DIR/bin/plog-converter" \
            -t errorfile \
            -o pvs-errorfile.txt \
            pvs-report.log

      - name: Upload PVS-Studio reports
        uses: actions/upload-artifact@v4
        with:
          name: pvs-reports
          path: |
            pvs-report.log
            pvs-errorfile.txt
