- uses: actions/checkout@v4

- name: Setup .NET 8.0
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.0.x

- name: Install dependencies
  run: dotnet restore

- name: Install PVS-Studio
  run: |
    wget https://files.viva64.com/pvs-studio-latest.tgz
    tar -xvzf pvs-studio-latest.tgz
    sudo ./pvs-studio/install.sh

- name: Build
  run: dotnet build --no-restore

- name: Run PVS-Studio analysis
  run: |
    pvs-studio-analyzer analyze -o pvs-report.log -- dotnet build
    plog-converter -t errorfile -o pvs-errorfile.txt pvs-report.log

- name: Upload PVS-Studio reports
  uses: actions/upload-artifact@v4
  with:
    name: pvs-reports
    path: |
      pvs-report.log
      pvs-errorfile.txt
