name: CI with PVS-Studio

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Download and extract PVS-Studio
        run: |
          wget https://files.viva64.com/pvs-studio-latest.tgz
          tar -xzf pvs-studio-latest.tgz

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

      - name: Run PVS-Studio analysis (no install)
        run: |
          PVS_DIR=$(echo pvs-studio-*-x86_64)
          echo "Using PVS-Studio from $PVS_DIR"
          $PVS_DIR/bin/pvs-studio-analyzer analyze -o pvs-report.log -- dotnet build --configuration Release
          $PVS_DIR/bin/plog-converter -t errorfile -o pvs-errorfile.txt pvs-report.log

      - name: Upload PVS-Studio reports
        uses: actions/upload-artifact@v4
        with:
          name: pvs-reports
          path: |
            pvs-report.log
            pvs-errorfile.txt
